#!/bin/sh
xsetroot -cursor_name left_ptr &
xset r rate 320 60 &
${HOME}/.fehbg &
dwm_status_bar &
setxkbmap br &
picom --corner-radius 5 &
dunst &
xautolock -time 2 -locker slock &
#emacs --daemon &
#emacs-29-vcs --daemon &
#exec startlxqt 
exec dwm
